replicaCount: 2
image:
  repository: vineetkumarsingh/auctionapi
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

env:
  MONGO_URI: ""
  JWT_SECRET: ""
  REFRESH_TOKEN_SECRET: ""