apiVersion: apps/v1
kind: Deployment
metadata:
  name: auctionapi
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: auctionapi
  template:
    metadata:
      labels:
        app: auctionapi
    spec:
      containers:
        - name: auctionapi
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8000
          env:
            - name: MONGO_URI
              value: "{{ .Values.env.MONGO_URI }}"
            - name: JWT_SECRET
              value: "{{ .Values.env.JWT_SECRET }}"
            - name: REFRESH_TOKEN_SECRET
              value: "{{ .Values.env.REFRESH_TOKEN_SECRET }}"